### ISSUE TITLE
tp-smapi on Ubuntu 16.04 LTS Enablement Stack

### ISSUE THREAD

**Issue by mvfcc** [evgeni/tp_smapi#33]
Hi,
I've got problem with the tp-smapi-dkms on Ubuntu 16.04 with 4.15 LTS Enablement Stack.

apt upgrade / install errors
> Setting up tp-smapi-dkms (0.42-1~xenial) ...
> Loading new tp_smapi-0.42 DKMS files...
> Building only for 4.15.0-32-generic
> Building initial module for 4.15.0-32-generic
> ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/tp-smapi-dkms.0.crash'
> Error! Bad return status for module build on kernel: 4.15.0-32-generic (x86_64)
> Consult /var/lib/dkms/tp_smapi/0.42/build/make.log for more information.

/var/lib/dkms/tp_smapi/0.42/build/make.log
> make: Entering directory '/usr/src/linux-headers-4.15.0-32-generic'
>   CC [M]  /var/lib/dkms/tp_smapi/0.42/build/thinkpad_ec.o
> /var/lib/dkms/tp_smapi/0.42/build/thinkpad_ec.c: In function ‘check_dmi_for_ec’:
> /var/lib/dkms/tp_smapi/0.42/build/thinkpad_ec.c:469:1: warning: the frame size of 1728 bytes is larger than 1024 bytes [-Wframe-larger-than=]
>  }
>  ^
>   CC [M]  /var/lib/dkms/tp_smapi/0.42/build/tp_smapi.o
>   CC [M]  /var/lib/dkms/tp_smapi/0.42/build/hdaps.o
> /var/lib/dkms/tp_smapi/0.42/build/hdaps.c: In function ‘hdaps_init’:
> /var/lib/dkms/tp_smapi/0.42/build/hdaps.c:781:2: error: implicit declaration of function ‘init_timer’ [-Werror=implicit-function-declaration]
>   init_timer(&hdaps_timer);
>   ^
> /var/lib/dkms/tp_smapi/0.42/build/hdaps.c:782:23: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
>   hdaps_timer.function = hdaps_mousedev_poll;
>                        ^
> cc1: some warnings being treated as errors
> scripts/Makefile.build:339: recipe for target '/var/lib/dkms/tp_smapi/0.42/build/hdaps.o' failed
> make[1]: *** [/var/lib/dkms/tp_smapi/0.42/build/hdaps.o] Error 1
> Makefile:1552: recipe for target '_module_/var/lib/dkms/tp_smapi/0.42/build' failed
> make: *** [_module_/var/lib/dkms/tp_smapi/0.42/build] Error 2
> make: Leaving directory '/usr/src/linux-headers-4.15.0-32-generic'

Can you help me?

**Comment by evgeni** [comment]
Yes, you need `tp-smapi` 0.43 for kernel 4.15, please ask Ubuntu to update their packages.
