### ISSUE TITLE
Errors on Linux 4.7, with T420

### ISSUE THREAD

**Issue by robinpaulson** [evgeni/tp_smapi#27]
Hi all, I'm having problems with kernel 4.7 and 4.8 in Ubuntu - it works fine with Linux 4.4. Errors as below:

apt errors:
```
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal
4.7.0-80-bfq /boot/vmlinuz-4.7.0-80-bfq
run-parts: executing /etc/kernel/postinst.d/dkms 4.7.0-80-bfq
/boot/vmlinuz-4.7.0-80-bfq
ERROR (dkms apport): kernel package linux-headers-4.7.0-80-bfq is not
supported
Error! Bad return status for module build on kernel: 4.7.0-80-bfq
(x86_64)
Consult /var/lib/dkms/tp-smapi/0.41/build/make.log for more information.
```

contents of /var/lib/dkms/tp-smapi/0.41/build/make.log:
```
DKMS make.log for tp-smapi-0.41 for kernel 4.7.0-80-bfq (x86_64)
Tue Oct 18 13:30:09 NZDT 2016
make: Entering directory '/usr/src/linux-headers-4.7.0-80-bfq'
  LD      /var/lib/dkms/tp-smapi/0.41/build/built-in.o
  CC [M]  /var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o
In file included from include/linux/module.h:18:0,
                 from /var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:33:
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c: In function
‘__check_force_io’:
include/linux/moduleparam.h:344:67: error: return from incompatible
pointer type [-Werror=incompatible-pointer-types]
  static inline type __always_unused *__check_##name(void) { return(p); }
                                                                   ^
include/linux/moduleparam.h:396:35: note: in expansion of macro
‘__param_check’
 #define param_check_bool(name, p) __param_check(name, p, bool)
                                   ^
include/linux/moduleparam.h:146:2: note: in expansion of macro
‘param_check_bool’
  param_check_##type(name, &(value));       \
  ^
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:100:1: note: in
expansion of macro ‘module_param_named’
 module_param_named(force_io, force_io, bool, 0600);
 ^
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c: In function
‘check_dmi_for_ec’:
/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.c:469:1: warning: the
frame size of 1720 bytes is larger than 1024 bytes [-Wframe-larger-than=]
 }
 ^
cc1: some warnings being treated as errors
scripts/Makefile.build:295: recipe for target
'/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o' failed
make[1]: *** [/var/lib/dkms/tp-smapi/0.41/build/thinkpad_ec.o] Error 1
Makefile:1458: recipe for target
'_module_/var/lib/dkms/tp-smapi/0.41/build' failed
make: *** [_module_/var/lib/dkms/tp-smapi/0.41/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.7.0-80-bfq'
```

The particular functionality I'm interested in is hdaps. I note from the readme, the t420 is only partially supported, in what way?
Cheers.

**Comment by evgeni** [comment]
Hi,

the compile error is fixed in https://github.com/evgeni/tp_smapi/commit/8f40fcf3d9a4bfb9c3dae1caa2107ea3a367a609 which is part of tp_smapi 0.42, which is shipped in Ubuntu 16.10 and newer. If you are running and older Ubuntu release, and they managed to ship a kernel without testing the out-of-tree modules: please yell at Ubuntu ;-)

As for features, yes, we probably should document that: on a T420 you should get a half-working battery control and no hdaps - sorry about that.

**Comment by robinpaulson** [comment]
Huh, interesting, I manually installed v0.42 and it works fine, including hdaps. I wrote a note on the bug report on launchpad, and see you did also.

Cheers
